#HACER QUELA CALCULADORA PUEDA ELEGIR N NUMEROS
#RECIBIR LOS NUMEROS CON UN SOLO INPUT, SEPARADOS POR COMAS
#ESCRIBE LOS NUMEROS A JUGAR CON ELLOS, SEPARADOS POR UNA COMA -> 5,6,5,5,6

# REALIZAR LA suma
# CALCULAR EL PRIMEDIO DE ODOS LOS NUMEROS
# CALCULAR LA multiplicacion DE TODOS LOS NUMEROS
# ELEVAR CADA UNO DE LOS NUMEROS AL elevar_cuadrado
# CALCULAR EL FACTORIAL DE CAD UNO DE LOS NUMEROS
